Added partition by in lag tests
calogica/dbt-expectations pull request #146
Opened 2022-02-26 15:34 UTC by Lucasthenoob

# Problem: 
Not possible to put partition by parameters in the following tests:
- [expect_column_values_to_be_increasing](https://github.com/calogica/dbt-expectations/blob/main/macros/schema_tests/column_values_basic/expect_column_values_to_be_increasing.sql)
- [expect_column_values_to_be_decreasing](https://github.com/calogica/dbt-expectations/blob/main/macros/schema_tests/column_values_basic/expect_column_values_to_be_decreasing.sql)

# Changes:
- Added an optional parameter which allow to partition by. 
- Updated the README.MD with accordingly

Please let me know if there is anything

2022-02-26 21:47 UTC, clausherther requested changes
Couple of changes re: partition column parameters.
Also, we'll need a test that actually uses these partitions in https://github.com/calogica/dbt-expectations/blob/main/integration_tests/models/schema_tests/schema.yml
I can help you with that if you've never done integration tests on dbt packages. Thanks!

2022-02-26 21:47 UTC, clausherther commented on README.md
> +      partition_columns: partition_col_1, partition_col_2 # (Optional: default is None)
Let's make `partition_columns` an actual list not a string, similar to https://github.com/calogica/dbt-expectations#expect_table_row_count_to_be_between

2022-02-26 21:47 UTC, clausherther commented on README.md
> +      partition_columns: partition_col_1, partition_col_2 # (Optional: default is None)
See comment above re: `partition_columns`

2022-02-26 21:47 UTC, clausherther commented on macros/schema_tests/column_values_basic/expect_column_values_to_be_decreasing.sql
> +{%- set partition_columns_list = partition_columns.split(',') %}
`partition_columns` should be a Jinja list, so no need to spilt.

2022-02-26 21:47 UTC, clausherther commented on macros/schema_tests/column_values_basic/expect_column_values_to_be_decreasing.sql
> +                (partition by {{ partition_columns }} order by sort_column)
Since `partition_columns` is a list, you'll need to either loop, or do a `.join(",")` (easier) here.

2022-02-26 21:47 UTC, clausherther commented on macros/schema_tests/column_values_basic/expect_column_values_to_be_increasing.sql
> +{%- set partition_columns_list = partition_columns.split(',') %}
Btw, this is never used, so the below doesn't run.

2022-03-04 20:06 UTC, Lucasthenoob commented
It should be good now.
Sorry I don't have dbt installed on my personal computer. 
I validated the test is working on my other one but I could not test the second commit: data creation and test implementation

2022-03-04 23:25 UTC, clausherther approved these changes
I made a few changes myself to help get this over the finish line. Hope that works for you!

2022-03-07 03:20 UTC, merged