[WIP] Add test for a percentage of rows to be null
calogica/dbt-expectations pull request #241
Opened 2023-02-09 07:45 UTC by danhphan

This [Work in Progress] PR addresses the issue #238 that will allow for percentage of rows to be null.

CC @clausherther Please let me know if it needs any further changes.

Thank you.

2023-02-09 08:12 UTC, danhphan commented
FYI: I have added a column named `col_null_percentage` in the `data_test.sql` file for testing purpose. This column have 4 rows including one null row. So the null percentage will be 1/4 = 0.25. And in the `integration_tests/models/schema_tests/schema.yml` file, added the test for that column will less than 0.3. Thank you.

```
      - name: col_null_percentage
        tests:
          - dbt_expectations.expect_column_null_percentage_to_be_less_than:
              value: 0.3
```

2023-02-10 05:28 UTC, danhphan commented
Hi @clausherther I am not sure why the CircleCI is still running. I run all `dbt test` on a local machine and it was quite fast (a couple of minutes).

Any suggestions on this. Thank you!

2023-02-10 05:30 UTC, clausherther commented
@danhphan I have to approve it first, will do now.

2023-02-10 05:31 UTC, clausherther commented
I'll take a look at the PR itself this weekend and give feedback then.

2023-02-14 15:50 UTC, clausherther commented
@danhphan I think you'll need to rebase to get CI to pass (I remove SQLFluff support for now since their latest release broke things). I wasn't able to rebase your branch from my side.

2023-02-14 16:34 UTC, clausherther requested changes

2023-02-14 16:41 UTC, clausherther commented
I was able to rebase your branch, but left comments re: the test.
I think essentially, we'd need to add those tolerance params to `expression_is_true`, which is a more extensive change than maybe you had in mind. Let me know if you want to try and tackle that, or if you'd rather have me help with that.

2023-02-16 22:42 UTC, danhphan commented
Hi @clausherther, yes, I think adding these tolerance params will allow better generalisation.

Let me work on that. If I face any issues, I will ask for your help :) Thank you.

2023-02-16 22:42 UTC, danhphan commented on macros/schema_tests/aggregate_functions/expect_column_null_percentage_to_be_less_than.sql
> +{% test expect_column_null_percentage_to_be_less_than(model,
Yes, agree!

2023-02-28 10:25 UTC, danhphan commented
I am thinking to change the [expression_is_true](https://github.com/calogica/dbt-expectations/blob/bd7746d8c818d5060446e21a959a15f6aa26dc10/macros/schema_tests/_generalized/expression_is_true.sql#L1) test to:

```
with grouped_expression as (
    ...
),

tolerance_expression as (
    select ( sum (expression is false) * 1.0 / count(*) ) < {{ tolerance_percent }} as tolerated_expression
    from
        grouped_expression    
) ,

validation_errors as (
    select
        *
    from
        tolerance_expression
    where
        not(tolerated_expression {{ test_condition }})
)

```

But not sure if it will work for the case when we have a `group_by_columns` parameter.

In addition, is there a test in the codebase for the case of using `group_by_columns` parameter in the `expression_is_true` test?

Thank you!

2023-09-01 15:45 UTC, closed without merging

2023-10-25 18:55 UTC, jenna-jordan commented
Just curious why this PR got closed, and whether there are any plans to add this feature? (we commonly test that, for example, >90% of values are not null, using Great Expectations)