dispactching expect_table_row_count_to_equal
calogica/dbt-expectations pull request #64
Opened 2021-05-11 22:25 UTC by alieus

dispactching `expect_table_row_count_to_equal` to create a shim to make it compatible with TSQL

2021-05-11 23:41 UTC, clausherther requested changes
Thanks for adding that, looks good! One small change: could we add spaces after commas in here, like so:
```
(model, value, row_condition=None)
```
Apologies if this isn't consistent elsewhere.

2021-05-11 23:43 UTC, clausherther requested changes
Sorry, actually, one more change:
We should not pass None in the dispatch, the main method already does this.
```
(model, value, row_condition)
```

2021-05-12 00:19 UTC, alieus commented
> Thanks for adding that, looks good! One small change: could we add spaces after commas in here, like so:
> 
> ```
> (model, value, row_condition=None)
> ```
> 
> Apologies if this isn't consistent elsewhere.

2021-05-20 14:03 UTC, clausherther commented
Hi @alieus! Anything else you need from me to make those changes?

2021-05-20 14:25 UTC, alieus commented
Hey @clausherther. I believe I made the changes you requested. This should be good to merge. Let me know if you think otherwise.

2021-05-20 15:17 UTC, clausherther requested changes

2021-05-20 15:17 UTC, clausherther commented on macros/schema_tests/table_shape/expect_table_row_count_to_equal.sql
>      {{ adapter.dispatch('test_expect_table_row_count_to_equal', packages=dbt_expectations._get_namespaces()) (model,value,row_condition=None) }}
Hey! Sorry, small thing: could we add spaces here as well like you did above?
Also, please keep the `None` default in the macro parameters, but take it out of the dispatch call.
```
{%- macro test_expect_table_row_count_to_equal(model, value, row_condition=None) -%}    
    {{ adapter.dispatch('test_expect_table_row_count_to_equal', packages=dbt_expectations._get_namespaces()) (model, value, row_condition) }}
```

2021-05-28 19:42 UTC, clausherther approved these changes
LGTM, thanks!

2021-05-28 19:42 UTC, merged